version: '3'

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ${WWW_ROOT}:/var/www
    ports:
      - "127.0.0.1:8030:80"
    links:
      - app
      - phpmyadmin

  app:
    build: .
    restart: unless-stopped
    volumes:
      - ${WWW_ROOT}:/var/www
    links:
      - mariadb
      - smtp

  mariadb:
    image: mariadb:10.7
    restart: always
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD

  rabbitmq:
    image: rabbitmq:3.8-management
    restart: always
    hostname: xem_rabbitmq
    ports:
      - "127.0.0.1:8089:15672"
    environment:
      RABBITMQ_DEFAULT_USER: $MQ_USERNAME
      RABBITMQ_DEFAULT_PASS: $MQ_PASSWORD
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_ABSOLUTE_URI: /root/phpmyadmin/
    links:
      - mariadb

  smtp:
    image: namshi/smtp
    restart: always
