parameters:
    locale: 'en'
    locales: ['en', 'nl']
    brand_name: 'The Xross Entity Map'
    email_sender_name: '%brand_name%'
    email_sender_address: '%env(SENDER_EMAIL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $allowedLocales: '%locales%'
            $defaultLocale: '%locale%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\EventSubscriber\:
        resource: '../src/EventSubscriber'
        tags: ['kernel.event_subscriber']

    App\Twig\Extension:
        tags:
            - { name: twig.extension }
